### ISSUE TITLE
"Build" step failed in Netlify (after dependencies upgrades)

### ISSUE THREAD

**Issue by nhoizey** [maxboeck/webmention-analytics#11]
I tried to create a new webmention analytics site with the Netlify button, and I get an error during "initializing" step.

It looks like there's an issue when it tries to build `node-sass` with `node-gyp`.

<details>
<summary>Log extract</summary>

```log
10:08:42 AM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
10:08:41 AM: npm ERR! code 1
10:08:41 AM: npm ERR! path /opt/build/repo/node_modules/node-sass
10:08:41 AM: npm ERR! command failed
10:08:41 AM: npm ERR! command sh -c node scripts/build.js
10:08:41 AM: npm ERR! Building: /opt/buildhome/.nvm/versions/node/v18.16.1/bin/node /opt/build/repo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
10:08:41 AM: npm ERR! make: Entering directory '/opt/build/repo/node_modules/node-sass/build'
10:08:41 AM: npm ERR!   g++ -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION=3.5.5' -I/opt/buildhome/.cache/node-gyp/18.16.1/include/node -I/opt/buildhome/.cache/node-gyp/18.16.1/src -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/openssl/config -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/openssl/openssl/include -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/uv/include -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/zlib -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++17 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c
10:08:41 AM: npm ERR!   g++ -o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o ../src/libsass/src/ast_fwd_decl.cpp '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION=3.5.5' -I/opt/buildhome/.cache/node-gyp/18.16.1/include/node -I/opt/buildhome/.cache/node-gyp/18.16.1/src -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/openssl/config -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/openssl/openssl/include -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/uv/include -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/zlib -I/opt/buildhome/.cache/node-gyp/18.16.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++17 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o.d.raw   -c```
```

</details>

**Comment by nhoizey** [comment]
Upgrading most dependencies and adding `memory-fs` fixed the installation/initialization part, but I now get a Webpack error during build:

```
11:05:26 AM: [eleventy:prod] TypeError: Cannot read properties of undefined (reading 'normal')
11:05:26 AM: [eleventy:prod]     at module.exports.compile (/opt/build/repo/src/assets/scripts/__scripts.11ty.js:63:28)
11:05:26 AM: [eleventy:prod]     at module.exports.render (/opt/build/repo/src/assets/scripts/__scripts.11ty.js:87:39)
11:05:26 AM: [eleventy:prod]     at JavaScript.<anonymous> (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:153:43)
11:05:26 AM: [eleventy:prod]     at Template._render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:514:28)
11:05:26 AM: [eleventy:prod]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
11:05:26 AM: [eleventy:prod]     at async Template.renderWithoutLayout (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:456:27)
11:05:26 AM: [eleventy:prod]     at async TemplateMap.populateContentDataInMap (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:589:39)
11:05:26 AM: [eleventy:prod]     at async TemplateMap.cache (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:483:5)
11:05:26 AM: [eleventy:prod]     at async TemplateWriter._createTemplateMap (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
11:05:26 AM: [eleventy:prod]     at async TemplateWriter.generateTemplates (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/assets/scripts/main.js from ./src/assets/scripts/__scripts.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/assets/styles/main.css from ./src/assets/styles/__styles.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
11:05:26 AM: [eleventy:prod] [11ty] 1. Having trouble writing to dist/assets/scripts/main.js from ./src/assets/scripts/__scripts.11ty.js (via EleventyTemplateError)
11:05:26 AM: [eleventy:prod] [11ty] 2. The return value from the render function for the 11ty.js template was not a String or Buffer. Received null (via Error)
11:05:26 AM: [eleventy:prod] [11ty]
11:05:26 AM: [eleventy:prod] [11ty] Original error stack trace: Error: The return value from the render function for the 11ty.js template was not a String or Buffer. Received null
11:05:26 AM: [eleventy:prod] [11ty]     at Template._write (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:757:13)
11:05:26 AM: [eleventy:prod] [11ty]     at async Promise.all (index 0)
11:05:26 AM: [eleventy:prod] [11ty]     at async Promise.all (index 1)
11:05:26 AM: [eleventy:prod] [11ty]     at async Eleventy.executeBuild (/opt/build/repo/node_modules/@11ty/eleventy/src/Eleventy.js:1191:13)
11:05:26 AM: [eleventy:prod] [11ty] Benchmark    378ms  19%     1× (Data) `./src/data/webmentions.js`
11:05:26 AM: [eleventy:prod] [11ty] Copied 10 files / Wrote 0 files in 1.08 seconds (v2.0.1)
11:05:28 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/404/index.html from ./src/404.njk
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-07/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-06/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-05/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-04/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-03/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-02/index.html from ./src/reports.11ty.js
11:05:26 AM: [eleventy:prod] [11ty] Writing dist/2023-01/index.html from ./src/reports.11ty.js
11:05:27 AM: [eleventy:prod] [11ty] Writing dist/index.html from ./src/index.njk
11:05:27 AM: ERROR: eleventy:prod exited with 1.
```

I don't know Webpack at all… 😞
